# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'InternHelper' do

pod 'Alamofire', '~> 3.3'
pod 'ObjectMapper', '~> 1.2'
pod 'AlamofireObjectMapper', '~> 3.0'
pod 'PromiseKit'
pod 'Socket.IO-Client-Swift'

end

