platform :ios, '9.0'
use_frameworks!

target 'Networking' do

	pod 'Alamofire'
    pod 'ObjectMapper'
    pod 'AlamofireObjectMapper'
    pod 'AlamofireNetworkActivityIndicator'
    
    pod 'Kingfisher'
    
    pod 'Socket.IO-Client-Swift'
    
    pod 'RealmSwift'
    
    pod 'PromiseKit', '~> 4.0'
    pod 'RxSwift',    '~> 3.0'
    pod 'RxCocoa',    '~> 3.0'
    pod 'RxRealm'
    pod 'RxAlamofire'
  
end