#!/bin/bash

install_bundler()
{
	echo ""
	echo "Install Bundler"
	echo " → Checking bundler"
	local isBundle
	isBundle=$(gem query -i -n bundler)

	if ! "$isBundle"; then
		echo " → Installing bundler"
		gem install bundler
	fi

	echo " → Bundler installed"
}

install_bundler_gems()
{
	echo ""
	echo " → Installing bundler gems dependencies"
	bundle i
}

install_cocoapods_pods()
{
	echo ""
	echo " → Installing Cocoapods dependencies"
	bundle e pod install
}

install_bundler
install_bundler_gems
install_cocoapods_pods








