platform :ios, '9.0'
use_frameworks!

target 'FirebaseTest' do

  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'

  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.13.4'

end
